import { Injectable } from "@angular/core";
import { Monster } from "../models/monster";

@Injectable({
  providedIn: "root",
})
export class MonsterService {
  monsters: Monster[] = [
    {
      name: "Aboleth",
      index: "aboleth",
      armor_class: [
        {
          value: 17,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful evil",
      charisma: 18,
      condition_immunities: [],
      proficiency_bonus: 4,
      challenge_rating: 10,
      constitution: 15,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 9,
    },
    {
      name: "Acolyte",
      index: "acolyte",
      armor_class: [
        {
          value: 10,
          type: "dex",
        },
      ],
      desc:
        "Acolytes are junior members of a clergy, usually answerable to a priest. They perform a variety of functions in a temple and are granted minor spellcasting power by their deities.",
      alignment: "any alignment",
      charisma: 11,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.25,
      constitution: 10,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Adult Bronze Dragon",
      index: "adult-bronze-dragon",
      armor_class: [
        {
          value: 19,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful good",
      charisma: 19,
      condition_immunities: [],
      proficiency_bonus: 5,
      challenge_rating: 15,
      constitution: 23,
      damage_immunities: ["lightning"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Adult Copper Dragon",
      index: "adult-copper-dragon",
      armor_class: [
        {
          value: 18,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "chaotic good",
      charisma: 17,
      condition_immunities: [],
      proficiency_bonus: 5,
      challenge_rating: 14,
      constitution: 21,
      damage_immunities: ["acid"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 12,
    },
    {
      name: "Adult Red Dragon",
      index: "adult-red-dragon",
      armor_class: [
        {
          value: 19,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "chaotic evil",
      charisma: 21,
      condition_immunities: [],
      proficiency_bonus: 6,
      challenge_rating: 17,
      constitution: 25,
      damage_immunities: ["fire"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Ancient Blue Dragon",
      index: "ancient-blue-dragon",
      armor_class: [
        {
          value: 22,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful evil",
      charisma: 21,
      condition_immunities: [],
      proficiency_bonus: 7,
      challenge_rating: 23,
      constitution: 27,
      damage_immunities: ["lightning"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Ancient Bronze Dragon",
      index: "ancient-bronze-dragon",
      armor_class: [
        {
          value: 22,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful good",
      charisma: 21,
      condition_immunities: [],
      proficiency_bonus: 7,
      challenge_rating: 22,
      constitution: 27,
      damage_immunities: ["lightning"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Ancient White Dragon",
      index: "ancient-white-dragon",
      armor_class: [
        {
          value: 20,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "chaotic evil",
      charisma: 14,
      condition_immunities: [],
      proficiency_bonus: 6,
      challenge_rating: 20,
      constitution: 26,
      damage_immunities: ["cold"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Ancient Silver Dragon",
      index: "ancient-silver-dragon",
      armor_class: [
        {
          value: 22,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful good",
      charisma: 23,
      condition_immunities: [],
      proficiency_bonus: 7,
      challenge_rating: 23,
      constitution: 29,
      damage_immunities: ["cold"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Ankheg",
      index: "ankheg",
      armor_class: [
        {
          value: 14,
          type: "natural",
        },
        {
          value: 11,
          type: "condition",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 6,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 13,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 11,
    },
    {
      name: "Bandit",
      index: "bandit",
      armor_class: [
        {
          value: 12,
          type: "armor",
        },
      ],
      desc:
        "**Bandits** rove in gangs and are sometimes led by thugs, veterans, or spellcasters. Not all bandits are evil. Oppression, drought, disease, or famine can often drive otherwise honest folk to a life of banditry.\n\n**Pirates** are bandits of the high seas. They might be freebooters interested only in treasure and murder, or they might be privateers sanctioned by the crown to attack and plunder an enemy nation’s vessels.",
      alignment: "any non-lawful alignment",
      charisma: 10,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.125,
      constitution: 12,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 12,
    },
    {
      name: "Balor",
      index: "balor",
      armor_class: [
        {
          value: 19,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "chaotic evil",
      charisma: 22,
      condition_immunities: [
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 6,
      challenge_rating: 19,
      constitution: 22,
      damage_immunities: ["fire", "poison"],
      damage_resistances: [
        "cold",
        "lightning",
        "bludgeoning, piercing, and slashing from nonmagical weapons",
      ],
      damage_vulnerabilities: [],
      dexterity: 15,
    },
    {
      name: "Berserker",
      index: "berserker",
      armor_class: [
        {
          value: 13,
          type: "armor",
        },
      ],
      desc: null,
      alignment: "any chaotic alignment",
      charisma: 9,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 17,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 12,
    },
    {
      name: "Black Pudding",
      index: "black-pudding",
      armor_class: [
        {
          value: 7,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 1,
      condition_immunities: [
        {
          name: "Blinded",
          desc: [
            "- A blinded creature can't see and automatically fails any ability check that requires sight.",
            "- Attack rolls against the creature have advantage, and the creature's attack rolls have disadvantage.",
          ],
        },
        {
          name: "Charmed",
          desc: [
            "- A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects.",
            "- The charmer has advantage on any ability check to interact socially with the creature.",
          ],
        },
        {
          name: "Exhaustion",
          desc: [
            "Some special abilities and environmental hazards, such as starvation and the long-term effects of freezing or scorching temperatures, can lead to a special condition called exhaustion. Exhaustion is measured in six levels. An effect can give a creature one or more levels of exhaustion, as specified in the effect's description.",
            "1 - Disadvantage on ability checks",
            "2 - Speed halved",
            "3 - Disadvantage on attack rolls and saving throws",
            "4 - Hit point maximum halved",
            "5 - Speed reduced to 0",
            "6 - Death",
            "If an already exhausted creature suffers another effect that causes exhaustion, its current level of exhaustion increases by the amount specified in the effect's description.",
            "A creature suffers the effect of its current level of exhaustion as well as all lower levels. For example, a creature suffering level 2 exhaustion has its speed halved and has disadvantage on ability checks.",
            "An effect that removes exhaustion reduces its level as specified in the effect's description, with all exhaustion effects ending if a creature's exhaustion level is reduced below 1.",
            "Finishing a long rest reduces a creature's exhaustion level by 1, provided that the creature has also ingested some food and drink.",
          ],
        },
        {
          name: "Frightened",
          desc: [
            "- A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.",
            "- The creature can't willingly move closer to the source of its fear.",
          ],
        },
        {
          name: "Prone",
          desc: [
            "- A prone creature's only movement option is to crawl, unless it stands up and thereby ends the condition.",
            "- The creature has disadvantage on attack rolls.",
            "- An attack roll against the creature has advantage if the attacker is within 5 feet of the creature. Otherwise, the attack roll has disadvantage.",
          ],
        },
      ],
      proficiency_bonus: 2,
      challenge_rating: 4,
      constitution: 16,
      damage_immunities: ["acid", "cold", "lightning", "slashing"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 5,
    },
    {
      name: "Black Dragon Wyrmling",
      index: "black-dragon-wyrmling",
      armor_class: [
        {
          value: 17,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "chaotic evil",
      charisma: 13,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 13,
      damage_immunities: ["acid"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 14,
    },
    {
      name: "Blue Dragon Wyrmling",
      index: "blue-dragon-wyrmling",
      armor_class: [
        {
          value: 17,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful evil",
      charisma: 15,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 3,
      constitution: 15,
      damage_immunities: ["lightning"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Cloaker",
      index: "cloaker",
      armor_class: [
        {
          value: 14,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "chaotic neutral",
      charisma: 14,
      condition_immunities: [],
      proficiency_bonus: 3,
      challenge_rating: 8,
      constitution: 12,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 15,
    },
    {
      name: "Cloud Giant",
      index: "cloud-giant",
      armor_class: [
        {
          value: 14,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "neutral good (50%) or neutral evil (50%)",
      charisma: 16,
      condition_immunities: [],
      proficiency_bonus: 4,
      challenge_rating: 9,
      constitution: 22,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Crocodile",
      index: "crocodile",
      armor_class: [
        {
          value: 12,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 5,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.5,
      constitution: 13,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Death Dog",
      index: "death-dog",
      armor_class: [
        {
          value: 12,
          type: "dex",
        },
      ],
      desc:
        "A death dog is an ugly two-headed hound that roams plains, and deserts. Hate burns in a death dog’s heart, and a taste for humanoid flesh drives it to attack travelers and explorers. Death dog saliva carries a foul disease that causes a victim’s flesh to slowly rot off the bone.",
      alignment: "neutral evil",
      charisma: 6,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 1,
      constitution: 14,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 14,
    },
    {
      name: "Draft Horse",
      index: "draft-horse",
      armor_class: [
        {
          value: 10,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 7,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.25,
      constitution: 12,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Dretch",
      index: "dretch",
      armor_class: [
        {
          value: 11,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "chaotic evil",
      charisma: 3,
      condition_immunities: [
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 2,
      challenge_rating: 0.25,
      constitution: 12,
      damage_immunities: ["poison"],
      damage_resistances: ["cold", "fire", "lightning"],
      damage_vulnerabilities: [],
      dexterity: 11,
    },
    {
      name: "Dryad",
      index: "dryad",
      armor_class: [
        {
          value: 11,
          type: "dex",
        },
        {
          value: 16,
          type: "spell",
        },
      ],
      desc: null,
      alignment: "neutral",
      charisma: 18,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 1,
      constitution: 11,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 12,
    },
    {
      name: "Dust Mephit",
      index: "dust-mephit",
      armor_class: [
        {
          value: 12,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "neutral evil",
      charisma: 10,
      condition_immunities: [
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 2,
      challenge_rating: 0.5,
      constitution: 10,
      damage_immunities: ["poison"],
      damage_resistances: [],
      damage_vulnerabilities: ["fire"],
      dexterity: 14,
    },
    {
      name: "Ettercap",
      index: "ettercap",
      armor_class: [
        {
          value: 13,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "neutral evil",
      charisma: 8,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 13,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 15,
    },
    {
      name: "Ghast",
      index: "ghast",
      armor_class: [
        {
          value: 13,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "chaotic evil",
      charisma: 8,
      condition_immunities: [
        {
          name: "Charmed",
          desc: [
            "- A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects.",
            "- The charmer has advantage on any ability check to interact socially with the creature.",
          ],
        },
        {
          name: "Exhaustion",
          desc: [
            "Some special abilities and environmental hazards, such as starvation and the long-term effects of freezing or scorching temperatures, can lead to a special condition called exhaustion. Exhaustion is measured in six levels. An effect can give a creature one or more levels of exhaustion, as specified in the effect's description.",
            "1 - Disadvantage on ability checks",
            "2 - Speed halved",
            "3 - Disadvantage on attack rolls and saving throws",
            "4 - Hit point maximum halved",
            "5 - Speed reduced to 0",
            "6 - Death",
            "If an already exhausted creature suffers another effect that causes exhaustion, its current level of exhaustion increases by the amount specified in the effect's description.",
            "A creature suffers the effect of its current level of exhaustion as well as all lower levels. For example, a creature suffering level 2 exhaustion has its speed halved and has disadvantage on ability checks.",
            "An effect that removes exhaustion reduces its level as specified in the effect's description, with all exhaustion effects ending if a creature's exhaustion level is reduced below 1.",
            "Finishing a long rest reduces a creature's exhaustion level by 1, provided that the creature has also ingested some food and drink.",
          ],
        },
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 10,
      damage_immunities: ["poison"],
      damage_resistances: ["necrotic"],
      damage_vulnerabilities: [],
      dexterity: 17,
    },
    {
      name: "Giant Ape",
      index: "giant-ape",
      armor_class: [
        {
          value: 12,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 7,
      condition_immunities: [],
      proficiency_bonus: 3,
      challenge_rating: 7,
      constitution: 18,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 14,
    },
    {
      name: "Ancient Black Dragon",
      index: "ancient-black-dragon",
      armor_class: [
        {
          value: 22,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "chaotic evil",
      charisma: 19,
      condition_immunities: [],
      proficiency_bonus: 7,
      challenge_rating: 21,
      constitution: 25,
      damage_immunities: ["acid"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 14,
    },
    {
      name: "Giant Badger",
      index: "giant-badger",
      armor_class: [
        {
          value: 10,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 5,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.25,
      constitution: 15,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Giant Boar",
      index: "giant-boar",
      armor_class: [
        {
          value: 12,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 5,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 16,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Giant Centipede",
      index: "giant-centipede",
      armor_class: [
        {
          value: 13,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 3,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.25,
      constitution: 12,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 14,
    },
    {
      name: "Ancient Copper Dragon",
      index: "ancient-copper-dragon",
      armor_class: [
        {
          value: 21,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "chaotic good",
      charisma: 19,
      condition_immunities: [],
      proficiency_bonus: 7,
      challenge_rating: 21,
      constitution: 25,
      damage_immunities: ["acid"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 12,
    },
    {
      name: "Giant Constrictor Snake",
      index: "giant-constrictor-snake",
      armor_class: [
        {
          value: 12,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 3,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 12,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 14,
    },
    {
      name: "Ape",
      index: "ape",
      armor_class: [
        {
          value: 12,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 7,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.5,
      constitution: 14,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 14,
    },
    {
      name: "Giant Eagle",
      index: "giant-eagle",
      armor_class: [
        {
          value: 13,
          type: "dex",
        },
      ],
      desc:
        "A giant eagle is a noble creature that speaks its own language and understands speech in the Common tongue. A mated pair of giant eagles typically has up to four eggs or young in their nest (treat the young as normal eagles).",
      alignment: "neutral good",
      charisma: 10,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 1,
      constitution: 13,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 17,
    },
    {
      name: "Awakened Shrub",
      index: "awakened-shrub",
      armor_class: [
        {
          value: 9,
          type: "dex",
        },
      ],
      desc:
        "An awakened shrub is an ordinary shrub given sentience and mobility by the awaken spell or similar magic.",
      alignment: "unaligned",
      charisma: 6,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0,
      constitution: 11,
      damage_immunities: [],
      damage_resistances: ["piercing"],
      damage_vulnerabilities: ["fire"],
      dexterity: 8,
    },
    {
      name: "Assassin",
      index: "assassin",
      armor_class: [
        {
          value: 15,
          type: "armor",
        },
      ],
      desc:
        "Trained in the use of poison, assassins are remorseless killers who work for nobles, guildmasters, sovereigns, and anyone else who can afford them.",
      alignment: "any non-good alignment",
      charisma: 10,
      condition_immunities: [],
      proficiency_bonus: 3,
      challenge_rating: 8,
      constitution: 14,
      damage_immunities: [],
      damage_resistances: ["poison"],
      damage_vulnerabilities: [],
      dexterity: 16,
    },
    {
      name: "Giant Fire Beetle",
      index: "giant-fire-beetle",
      armor_class: [
        {
          value: 13,
          type: "natural",
        },
      ],
      desc:
        "A giant fire beetle is a nocturnal creature that takes its name from a pair of glowing glands that give off light. Miners and adventurers prize these creatures, for a giant fire beetle’s glands continue to shed light for 1d6 days after the beetle dies. Giant fire beetles are most commonly found underground and in dark forests.",
      alignment: "unaligned",
      charisma: 3,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0,
      constitution: 12,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Giant Lizard",
      index: "giant-lizard",
      armor_class: [
        {
          value: 12,
          type: "natural",
        },
      ],
      desc:
        "A giant lizard can be ridden or used as a draft animal. Lizardfolk also keep them as pets, and subterranean giant lizards are used as mounts and pack animals by drow, duergar, and others.",
      alignment: "unaligned",
      charisma: 5,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.25,
      constitution: 13,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 12,
    },
    {
      name: "Barbed Devil",
      index: "barbed-devil",
      armor_class: [
        {
          value: 15,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful evil",
      charisma: 14,
      condition_immunities: [
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 3,
      challenge_rating: 5,
      constitution: 18,
      damage_immunities: ["fire", "poison"],
      damage_resistances: [
        "cold",
        "bludgeoning, piercing, and slashing from nonmagical weapons that aren't silvered",
      ],
      damage_vulnerabilities: [],
      dexterity: 17,
    },
    {
      name: "Bearded Devil",
      index: "bearded-devil",
      armor_class: [
        {
          value: 13,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful evil",
      charisma: 11,
      condition_immunities: [
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 2,
      challenge_rating: 3,
      constitution: 15,
      damage_immunities: ["fire", "poison"],
      damage_resistances: [
        "cold",
        "bludgeoning, piercing, and slashing from nonmagical weapons that aren't silvered",
      ],
      damage_vulnerabilities: [],
      dexterity: 15,
    },
    {
      name: "Giant Sea Horse",
      index: "giant-sea-horse",
      armor_class: [
        {
          value: 13,
          type: "natural",
        },
      ],
      desc:
        "Like their smaller kin, giant sea horses are shy, colorful fish with elongated bodies and curled tails. Aquatic elves train them as mounts.",
      alignment: "unaligned",
      charisma: 5,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.5,
      constitution: 11,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 15,
    },
    {
      name: "Giant Shark",
      index: "giant-shark",
      armor_class: [
        {
          value: 13,
          type: "natural",
        },
      ],
      desc:
        "A giant shark is 30 feet long and normally found in deep oceans. Utterly fearless, it preys on anything that crosses its path, including whales and ships.",
      alignment: "unaligned",
      charisma: 5,
      condition_immunities: [],
      proficiency_bonus: 3,
      challenge_rating: 5,
      constitution: 21,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 11,
    },
    {
      name: "Blood Hawk",
      index: "blood-hawk",
      armor_class: [
        {
          value: 12,
          type: "dex",
        },
      ],
      desc:
        "Taking its name from its crimson feathers and aggressive nature, the blood hawk fearlessly attacks almost any animal, stabbing it with its daggerlike beak. Blood hawks flock together in large numbers, attacking as a pack to take down prey.",
      alignment: "unaligned",
      charisma: 5,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.125,
      constitution: 10,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 14,
    },
    {
      name: "Boar",
      index: "boar",
      armor_class: [
        {
          value: 11,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 5,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.25,
      constitution: 12,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 11,
    },
    {
      name: "Giant Vulture",
      index: "giant-vulture",
      armor_class: [
        {
          value: 10,
          type: "dex",
        },
      ],
      desc:
        "A giant vulture has advanced intelligence and a malevolent bent. Unlike its smaller kin, it will attack a wounded creature to hasten its end. Giant vultures have been known to haunt a thirsty, starving creature for days to enjoy its suffering.",
      alignment: "neutral evil",
      charisma: 7,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 1,
      constitution: 15,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Gnoll",
      index: "gnoll",
      armor_class: [
        {
          value: 15,
          type: "armor",
        },
      ],
      desc: null,
      alignment: "chaotic evil",
      charisma: 7,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.5,
      constitution: 11,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 12,
    },
    {
      name: "Bone Devil",
      index: "bone-devil",
      armor_class: [
        {
          value: 19,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful evil",
      charisma: 16,
      condition_immunities: [
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 4,
      challenge_rating: 9,
      constitution: 18,
      damage_immunities: ["fire", "poison"],
      damage_resistances: [
        "cold",
        "bludgeoning, piercing, and slashing from nonmagical weapons that aren't silvered",
      ],
      damage_vulnerabilities: [],
      dexterity: 16,
    },
    {
      name: "Camel",
      index: "camel",
      armor_class: [
        {
          value: 9,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 5,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.125,
      constitution: 14,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 8,
    },
    {
      name: "Hippogriff",
      index: "hippogriff",
      armor_class: [
        {
          value: 11,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 8,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 1,
      constitution: 13,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 13,
    },
    {
      name: "Hunter Shark",
      index: "hunter-shark",
      armor_class: [
        {
          value: 12,
          type: "dex",
        },
      ],
      desc:
        "Smaller than a giant shark but larger and fiercer than a reef shark, a hunter shark haunts deep waters. It usually hunts alone, but multiple hunter sharks might feed in the same area. A fully grown hunter shark is 15 to 20 feet long.",
      alignment: "unaligned",
      charisma: 4,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 15,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 13,
    },
    {
      name: "Chain Devil",
      index: "chain-devil",
      armor_class: [
        {
          value: 16,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful evil",
      charisma: 14,
      condition_immunities: [
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 3,
      challenge_rating: 8,
      constitution: 18,
      damage_immunities: ["fire", "poison"],
      damage_resistances: [
        "cold",
        "bludgeoning, piercing, and slashing from nonmagical weapons that aren't silvered",
      ],
      damage_vulnerabilities: [],
      dexterity: 15,
    },
    {
      name: "Iron Golem",
      index: "iron-golem",
      armor_class: [
        {
          value: 20,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 1,
      condition_immunities: [
        {
          name: "Charmed",
          desc: [
            "- A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects.",
            "- The charmer has advantage on any ability check to interact socially with the creature.",
          ],
        },
        {
          name: "Exhaustion",
          desc: [
            "Some special abilities and environmental hazards, such as starvation and the long-term effects of freezing or scorching temperatures, can lead to a special condition called exhaustion. Exhaustion is measured in six levels. An effect can give a creature one or more levels of exhaustion, as specified in the effect's description.",
            "1 - Disadvantage on ability checks",
            "2 - Speed halved",
            "3 - Disadvantage on attack rolls and saving throws",
            "4 - Hit point maximum halved",
            "5 - Speed reduced to 0",
            "6 - Death",
            "If an already exhausted creature suffers another effect that causes exhaustion, its current level of exhaustion increases by the amount specified in the effect's description.",
            "A creature suffers the effect of its current level of exhaustion as well as all lower levels. For example, a creature suffering level 2 exhaustion has its speed halved and has disadvantage on ability checks.",
            "An effect that removes exhaustion reduces its level as specified in the effect's description, with all exhaustion effects ending if a creature's exhaustion level is reduced below 1.",
            "Finishing a long rest reduces a creature's exhaustion level by 1, provided that the creature has also ingested some food and drink.",
          ],
        },
        {
          name: "Frightened",
          desc: [
            "- A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.",
            "- The creature can't willingly move closer to the source of its fear.",
          ],
        },
        {
          name: "Paralyzed",
          desc: [
            "- A paralyzed creature is incapacitated (see the condition) and can't move or speak.",
            "- The creature automatically fails Strength and Dexterity saving throws.",
            "- Attack rolls against the creature have advantage.",
            "- Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature.",
          ],
        },
        {
          name: "Petrified",
          desc: [
            "- A petrified creature is transformed, along with any nonmagical object it is wearing or carrying, into a solid inanimate substance (usually stone). Its weight increases by a factor of ten, and it ceases aging.",
            "- The creature is incapacitated (see the condition), can't move or speak, and is unaware of its surroundings.",
            "- Attack rolls against the creature have advantage.",
            "- The creature automatically fails Strength and Dexterity saving throws.",
            "- The creature has resistance to all damage.",
            "- The creature is immune to poison and disease, although a poison or disease already in its system is suspended, not neutralized.",
          ],
        },
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 5,
      challenge_rating: 16,
      constitution: 20,
      damage_immunities: [
        "fire",
        "poison",
        "psychic",
        "bludgeoning, piercing, and slashing from nonmagical weapons that aren't adamantine",
      ],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 9,
    },
    {
      name: "Chuul",
      index: "chuul",
      armor_class: [
        {
          value: 16,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "chaotic evil",
      charisma: 5,
      condition_immunities: [
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 2,
      challenge_rating: 4,
      constitution: 16,
      damage_immunities: ["poison"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Clay Golem",
      index: "clay-golem",
      armor_class: [
        {
          value: 14,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 1,
      condition_immunities: [
        {
          name: "Charmed",
          desc: [
            "- A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects.",
            "- The charmer has advantage on any ability check to interact socially with the creature.",
          ],
        },
        {
          name: "Exhaustion",
          desc: [
            "Some special abilities and environmental hazards, such as starvation and the long-term effects of freezing or scorching temperatures, can lead to a special condition called exhaustion. Exhaustion is measured in six levels. An effect can give a creature one or more levels of exhaustion, as specified in the effect's description.",
            "1 - Disadvantage on ability checks",
            "2 - Speed halved",
            "3 - Disadvantage on attack rolls and saving throws",
            "4 - Hit point maximum halved",
            "5 - Speed reduced to 0",
            "6 - Death",
            "If an already exhausted creature suffers another effect that causes exhaustion, its current level of exhaustion increases by the amount specified in the effect's description.",
            "A creature suffers the effect of its current level of exhaustion as well as all lower levels. For example, a creature suffering level 2 exhaustion has its speed halved and has disadvantage on ability checks.",
            "An effect that removes exhaustion reduces its level as specified in the effect's description, with all exhaustion effects ending if a creature's exhaustion level is reduced below 1.",
            "Finishing a long rest reduces a creature's exhaustion level by 1, provided that the creature has also ingested some food and drink.",
          ],
        },
        {
          name: "Frightened",
          desc: [
            "- A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.",
            "- The creature can't willingly move closer to the source of its fear.",
          ],
        },
        {
          name: "Paralyzed",
          desc: [
            "- A paralyzed creature is incapacitated (see the condition) and can't move or speak.",
            "- The creature automatically fails Strength and Dexterity saving throws.",
            "- Attack rolls against the creature have advantage.",
            "- Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature.",
          ],
        },
        {
          name: "Petrified",
          desc: [
            "- A petrified creature is transformed, along with any nonmagical object it is wearing or carrying, into a solid inanimate substance (usually stone). Its weight increases by a factor of ten, and it ceases aging.",
            "- The creature is incapacitated (see the condition), can't move or speak, and is unaware of its surroundings.",
            "- Attack rolls against the creature have advantage.",
            "- The creature automatically fails Strength and Dexterity saving throws.",
            "- The creature has resistance to all damage.",
            "- The creature is immune to poison and disease, although a poison or disease already in its system is suspended, not neutralized.",
          ],
        },
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 4,
      challenge_rating: 9,
      constitution: 18,
      damage_immunities: [
        "acid",
        "poison",
        "psychic",
        "bludgeoning, piercing, and slashing from nonmagical weapons that aren't adamantine",
      ],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 9,
    },
    {
      name: "Lizardfolk",
      index: "lizardfolk",
      armor_class: [
        {
          value: 13,
          type: "natural",
        },
        {
          value: 15,
          type: "armor",
        },
      ],
      desc: null,
      alignment: "neutral",
      charisma: 7,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.5,
      constitution: 13,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Manticore",
      index: "manticore",
      armor_class: [
        {
          value: 14,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful evil",
      charisma: 8,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 3,
      constitution: 17,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 16,
    },
    {
      name: "Cockatrice",
      index: "cockatrice",
      armor_class: [
        {
          value: 11,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 5,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.5,
      constitution: 12,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 12,
    },
    {
      name: "Chimera",
      index: "chimera",
      armor_class: [
        {
          value: 14,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "chaotic evil",
      charisma: 10,
      condition_immunities: [],
      proficiency_bonus: 3,
      challenge_rating: 6,
      constitution: 19,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 11,
    },
    {
      name: "Medusa",
      index: "medusa",
      armor_class: [
        {
          value: 15,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful evil",
      charisma: 15,
      condition_immunities: [],
      proficiency_bonus: 3,
      challenge_rating: 6,
      constitution: 16,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 15,
    },
    {
      name: "Merrow",
      index: "merrow",
      armor_class: [
        {
          value: 13,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "chaotic evil",
      charisma: 9,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 15,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Cultist",
      index: "cultist",
      armor_class: [
        {
          value: 12,
          type: "armor",
        },
      ],
      desc:
        "Cultists swear allegiance to dark powers such as elemental princes, demon lords, or archdevils. Most conceal their loyalties to avoid being ostracized, imprisoned, or executed for their beliefs. Unlike evil acolytes, cultists often show signs of insanity in their beliefs and practices.",
      alignment: "any non-good alignment",
      charisma: 10,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.125,
      constitution: 10,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 12,
    },
    {
      name: "Cult Fanatic",
      index: "cult-fanatic",
      armor_class: [
        {
          value: 13,
          type: "armor",
        },
      ],
      desc:
        "Fanatics are often part of a cult’s leadership, using their charisma and dogma to influence and prey on those of weak will. Most are interested in personal power above all else.",
      alignment: "any non-good alignment",
      charisma: 14,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 12,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 14,
    },
    {
      name: "Mummy",
      index: "mummy",
      armor_class: [
        {
          value: 11,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful evil",
      charisma: 12,
      condition_immunities: [
        {
          name: "Charmed",
          desc: [
            "- A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects.",
            "- The charmer has advantage on any ability check to interact socially with the creature.",
          ],
        },
        {
          name: "Exhaustion",
          desc: [
            "Some special abilities and environmental hazards, such as starvation and the long-term effects of freezing or scorching temperatures, can lead to a special condition called exhaustion. Exhaustion is measured in six levels. An effect can give a creature one or more levels of exhaustion, as specified in the effect's description.",
            "1 - Disadvantage on ability checks",
            "2 - Speed halved",
            "3 - Disadvantage on attack rolls and saving throws",
            "4 - Hit point maximum halved",
            "5 - Speed reduced to 0",
            "6 - Death",
            "If an already exhausted creature suffers another effect that causes exhaustion, its current level of exhaustion increases by the amount specified in the effect's description.",
            "A creature suffers the effect of its current level of exhaustion as well as all lower levels. For example, a creature suffering level 2 exhaustion has its speed halved and has disadvantage on ability checks.",
            "An effect that removes exhaustion reduces its level as specified in the effect's description, with all exhaustion effects ending if a creature's exhaustion level is reduced below 1.",
            "Finishing a long rest reduces a creature's exhaustion level by 1, provided that the creature has also ingested some food and drink.",
          ],
        },
        {
          name: "Frightened",
          desc: [
            "- A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.",
            "- The creature can't willingly move closer to the source of its fear.",
          ],
        },
        {
          name: "Paralyzed",
          desc: [
            "- A paralyzed creature is incapacitated (see the condition) and can't move or speak.",
            "- The creature automatically fails Strength and Dexterity saving throws.",
            "- Attack rolls against the creature have advantage.",
            "- Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature.",
          ],
        },
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 2,
      challenge_rating: 3,
      constitution: 15,
      damage_immunities: ["necrotic", "poison"],
      damage_resistances: [
        "bludgeoning, piercing, and slashing from nonmagical weapons",
      ],
      damage_vulnerabilities: ["fire"],
      dexterity: 8,
    },
    {
      name: "Merfolk",
      index: "merfolk",
      armor_class: [
        {
          value: 11,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "neutral",
      charisma: 12,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.125,
      constitution: 12,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 13,
    },
    {
      name: "Deva",
      index: "deva",
      armor_class: [
        {
          value: 17,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful good",
      charisma: 20,
      condition_immunities: [
        {
          name: "Charmed",
          desc: [
            "- A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects.",
            "- The charmer has advantage on any ability check to interact socially with the creature.",
          ],
        },
        {
          name: "Exhaustion",
          desc: [
            "Some special abilities and environmental hazards, such as starvation and the long-term effects of freezing or scorching temperatures, can lead to a special condition called exhaustion. Exhaustion is measured in six levels. An effect can give a creature one or more levels of exhaustion, as specified in the effect's description.",
            "1 - Disadvantage on ability checks",
            "2 - Speed halved",
            "3 - Disadvantage on attack rolls and saving throws",
            "4 - Hit point maximum halved",
            "5 - Speed reduced to 0",
            "6 - Death",
            "If an already exhausted creature suffers another effect that causes exhaustion, its current level of exhaustion increases by the amount specified in the effect's description.",
            "A creature suffers the effect of its current level of exhaustion as well as all lower levels. For example, a creature suffering level 2 exhaustion has its speed halved and has disadvantage on ability checks.",
            "An effect that removes exhaustion reduces its level as specified in the effect's description, with all exhaustion effects ending if a creature's exhaustion level is reduced below 1.",
            "Finishing a long rest reduces a creature's exhaustion level by 1, provided that the creature has also ingested some food and drink.",
          ],
        },
        {
          name: "Frightened",
          desc: [
            "- A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.",
            "- The creature can't willingly move closer to the source of its fear.",
          ],
        },
      ],
      proficiency_bonus: 4,
      challenge_rating: 10,
      constitution: 18,
      damage_immunities: [],
      damage_resistances: [
        "radiant",
        "bludgeoning, piercing, and slashing from nonmagical weapons",
      ],
      damage_vulnerabilities: [],
      dexterity: 18,
    },
    {
      name: "Druid",
      index: "druid",
      armor_class: [
        {
          value: 11,
          type: "dex",
        },
        {
          value: 16,
          type: "spell",
        },
      ],
      desc:
        "**Druids** dwell in forests and other secluded wilderness locations, where they protect the natural world from monsters and the encroachment of civilization. Some are **tribal shamans** who heal the sick, pray to animal spirits, and provide spiritual guidance.",
      alignment: "any alignment",
      charisma: 11,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 13,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 12,
    },
    {
      name: "Ogre Zombie",
      index: "ogre-zombie",
      armor_class: [
        {
          value: 8,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "neutral evil",
      charisma: 5,
      condition_immunities: [
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 18,
      damage_immunities: ["poison"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 6,
    },
    {
      name: "Owl",
      index: "owl",
      armor_class: [
        {
          value: 11,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 7,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0,
      constitution: 8,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 13,
    },
    {
      name: "Djinni",
      index: "djinni",
      armor_class: [
        {
          value: 17,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "chaotic good",
      charisma: 20,
      condition_immunities: [],
      proficiency_bonus: 4,
      challenge_rating: 11,
      constitution: 22,
      damage_immunities: ["lightning", "thunder"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 15,
    },
    {
      name: "Elk",
      index: "elk",
      armor_class: [
        {
          value: 10,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 6,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.25,
      constitution: 12,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Otyugh",
      index: "otyugh",
      armor_class: [
        {
          value: 14,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "neutral",
      charisma: 6,
      condition_immunities: [],
      proficiency_bonus: 3,
      challenge_rating: 5,
      constitution: 19,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 11,
    },
    {
      name: "Pegasus",
      index: "pegasus",
      armor_class: [
        {
          value: 12,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "chaotic good",
      charisma: 13,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 16,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 15,
    },
    {
      name: "Efreeti",
      index: "efreeti",
      armor_class: [
        {
          value: 17,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful evil",
      charisma: 16,
      condition_immunities: [],
      proficiency_bonus: 4,
      challenge_rating: 11,
      constitution: 24,
      damage_immunities: ["fire"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 12,
    },
    {
      name: "Ettin",
      index: "ettin",
      armor_class: [
        {
          value: 12,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "chaotic evil",
      charisma: 8,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 4,
      constitution: 17,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 8,
    },
    {
      name: "Oni",
      index: "oni",
      armor_class: [
        {
          value: 16,
          type: "armor",
        },
      ],
      desc: null,
      alignment: "lawful evil",
      charisma: 15,
      condition_immunities: [],
      proficiency_bonus: 3,
      challenge_rating: 7,
      constitution: 16,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 11,
    },
    {
      name: "Pit Fiend",
      index: "pit-fiend",
      armor_class: [
        {
          value: 19,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful evil",
      charisma: 24,
      condition_immunities: [
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 6,
      challenge_rating: 20,
      constitution: 24,
      damage_immunities: ["fire", "poison"],
      damage_resistances: [
        "cold",
        "bludgeoning, piercing, and slashing from nonmagical weapons that aren't silvered",
      ],
      damage_vulnerabilities: [],
      dexterity: 14,
    },
    {
      name: "Flying Snake",
      index: "flying-snake",
      armor_class: [
        {
          value: 14,
          type: "dex",
        },
      ],
      desc:
        "A flying snake is a brightly colored, winged serpent found in remote jungles. Tribespeople and cultists sometimes domesticate flying snakes to serve as messengers that deliver scrolls wrapped in their coils.",
      alignment: "unaligned",
      charisma: 5,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.125,
      constitution: 11,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 18,
    },
    {
      name: "Erinyes",
      index: "erinyes",
      armor_class: [
        {
          value: 18,
          type: "armor",
        },
      ],
      desc: null,
      alignment: "lawful evil",
      charisma: 18,
      condition_immunities: [
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 4,
      challenge_rating: 12,
      constitution: 18,
      damage_immunities: ["fire", "poison"],
      damage_resistances: [
        "cold",
        "bludgeoning, piercing, and slashing from nonmagical weapons that aren't silvered",
      ],
      damage_vulnerabilities: [],
      dexterity: 16,
    },
    {
      name: "Priest",
      index: "priest",
      armor_class: [
        {
          value: 13,
          type: "armor",
        },
      ],
      desc:
        "Priests bring the teachings of their gods to the common folk. They are the spiritual leaders of temples and shrines and often hold positions of influence in their communities. Evil priests might work openly under a tyrant, or they might be the leaders of religious sects hidden in the shadows of good society, overseeing depraved rites.\n\nA priest typically has one or more acolytes to help with religious ceremonies and other sacred duties.",
      alignment: "any alignment",
      charisma: 13,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 12,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Quipper",
      index: "quipper",
      armor_class: [
        {
          value: 13,
          type: "dex",
        },
      ],
      desc:
        "A quipper is a carnivorous fish with sharp teeth. Quippers can adapt to any aquatic environment, including cold subterranean lakes. They frequently gather in swarms; the statistics for a swarm of quippers appear later in this appendix.",
      alignment: "unaligned",
      charisma: 2,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0,
      constitution: 9,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 16,
    },
    {
      name: "Ghoul",
      index: "ghoul",
      armor_class: [
        {
          value: 12,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "chaotic evil",
      charisma: 6,
      condition_immunities: [
        {
          name: "Charmed",
          desc: [
            "- A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects.",
            "- The charmer has advantage on any ability check to interact socially with the creature.",
          ],
        },
        {
          name: "Exhaustion",
          desc: [
            "Some special abilities and environmental hazards, such as starvation and the long-term effects of freezing or scorching temperatures, can lead to a special condition called exhaustion. Exhaustion is measured in six levels. An effect can give a creature one or more levels of exhaustion, as specified in the effect's description.",
            "1 - Disadvantage on ability checks",
            "2 - Speed halved",
            "3 - Disadvantage on attack rolls and saving throws",
            "4 - Hit point maximum halved",
            "5 - Speed reduced to 0",
            "6 - Death",
            "If an already exhausted creature suffers another effect that causes exhaustion, its current level of exhaustion increases by the amount specified in the effect's description.",
            "A creature suffers the effect of its current level of exhaustion as well as all lower levels. For example, a creature suffering level 2 exhaustion has its speed halved and has disadvantage on ability checks.",
            "An effect that removes exhaustion reduces its level as specified in the effect's description, with all exhaustion effects ending if a creature's exhaustion level is reduced below 1.",
            "Finishing a long rest reduces a creature's exhaustion level by 1, provided that the creature has also ingested some food and drink.",
          ],
        },
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 2,
      challenge_rating: 1,
      constitution: 10,
      damage_immunities: ["poison"],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 15,
    },
    {
      name: "Ghost",
      index: "ghost",
      armor_class: [
        {
          value: 11,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "any alignment",
      charisma: 17,
      condition_immunities: [
        {
          name: "Charmed",
          desc: [
            "- A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects.",
            "- The charmer has advantage on any ability check to interact socially with the creature.",
          ],
        },
        {
          name: "Exhaustion",
          desc: [
            "Some special abilities and environmental hazards, such as starvation and the long-term effects of freezing or scorching temperatures, can lead to a special condition called exhaustion. Exhaustion is measured in six levels. An effect can give a creature one or more levels of exhaustion, as specified in the effect's description.",
            "1 - Disadvantage on ability checks",
            "2 - Speed halved",
            "3 - Disadvantage on attack rolls and saving throws",
            "4 - Hit point maximum halved",
            "5 - Speed reduced to 0",
            "6 - Death",
            "If an already exhausted creature suffers another effect that causes exhaustion, its current level of exhaustion increases by the amount specified in the effect's description.",
            "A creature suffers the effect of its current level of exhaustion as well as all lower levels. For example, a creature suffering level 2 exhaustion has its speed halved and has disadvantage on ability checks.",
            "An effect that removes exhaustion reduces its level as specified in the effect's description, with all exhaustion effects ending if a creature's exhaustion level is reduced below 1.",
            "Finishing a long rest reduces a creature's exhaustion level by 1, provided that the creature has also ingested some food and drink.",
          ],
        },
        {
          name: "Frightened",
          desc: [
            "- A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.",
            "- The creature can't willingly move closer to the source of its fear.",
          ],
        },
        {
          name: "Grappled",
          desc: [
            "- A grappled creature's speed becomes 0, and it can't benefit from any bonus to its speed.",
            "- The condition ends if the grappler is incapacitated (see the condition).",
            "- The condition also ends if an effect removes the grappled creature from the reach of the grappler or grappling effect, such as when a creature is hurled away by the thunderwave spell.",
          ],
        },
        {
          name: "Paralyzed",
          desc: [
            "- A paralyzed creature is incapacitated (see the condition) and can't move or speak.",
            "- The creature automatically fails Strength and Dexterity saving throws.",
            "- Attack rolls against the creature have advantage.",
            "- Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature.",
          ],
        },
        {
          name: "Petrified",
          desc: [
            "- A petrified creature is transformed, along with any nonmagical object it is wearing or carrying, into a solid inanimate substance (usually stone). Its weight increases by a factor of ten, and it ceases aging.",
            "- The creature is incapacitated (see the condition), can't move or speak, and is unaware of its surroundings.",
            "- Attack rolls against the creature have advantage.",
            "- The creature automatically fails Strength and Dexterity saving throws.",
            "- The creature has resistance to all damage.",
            "- The creature is immune to poison and disease, although a poison or disease already in its system is suspended, not neutralized.",
          ],
        },
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
        {
          name: "Prone",
          desc: [
            "- A prone creature's only movement option is to crawl, unless it stands up and thereby ends the condition.",
            "- The creature has disadvantage on attack rolls.",
            "- An attack roll against the creature has advantage if the attacker is within 5 feet of the creature. Otherwise, the attack roll has disadvantage.",
          ],
        },
        {
          name: "Restrained",
          desc: [
            "- A restrained creature's speed becomes 0, and it can't benefit from any bonus to its speed.",
            "- Attack rolls against the creature have advantage, and the creature's attack rolls have disadvantage.",
            "- The creature has disadvantage on Dexterity saving throws.",
          ],
        },
      ],
      proficiency_bonus: 2,
      challenge_rating: 4,
      constitution: 10,
      damage_immunities: ["cold", "necrotic", "poison"],
      damage_resistances: [
        "acid",
        "fire",
        "lightning",
        "thunder",
        "bludgeoning, piercing, and slashing from nonmagical weapons",
      ],
      damage_vulnerabilities: [],
      dexterity: 13,
    },
    {
      name: "Rhinoceros",
      index: "rhinoceros",
      armor_class: [
        {
          value: 11,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 6,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 15,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 8,
    },
    {
      name: "Reef Shark",
      index: "reef-shark",
      armor_class: [
        {
          value: 12,
          type: "natural",
        },
      ],
      desc:
        "Smaller than giant sharks and hunter sharks, reef sharks inhabit shallow waters and coral reefs, gathering in small packs to hunt. A full-grown specimen measures 6 to 10 feet long.",
      alignment: "unaligned",
      charisma: 4,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.5,
      constitution: 13,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 13,
    },
    {
      name: "Giant Crocodile",
      index: "giant-crocodile",
      armor_class: [
        {
          value: 14,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 7,
      condition_immunities: [],
      proficiency_bonus: 3,
      challenge_rating: 5,
      constitution: 17,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 9,
    },
    {
      name: "Giant Elk",
      index: "giant-elk",
      armor_class: [
        {
          value: 14,
          type: "natural",
        },
      ],
      desc:
        "The majestic giant elk is rare to the point that its appearance is often taken as a foreshadowing of an important event, such as the birth of a king. Legends tell of gods that take the form of giant elk when visiting the Material Plane. Many cultures therefore believe that to hunt these creatures is to invite divine wrath.",
      alignment: "unaligned",
      charisma: 10,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 14,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 16,
    },
    {
      name: "Roc",
      index: "roc",
      armor_class: [
        {
          value: 15,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 9,
      condition_immunities: [],
      proficiency_bonus: 4,
      challenge_rating: 11,
      constitution: 20,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 10,
    },
    {
      name: "Rust Monster",
      index: "rust-monster",
      armor_class: [
        {
          value: 14,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 6,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.5,
      constitution: 13,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 12,
    },
    {
      name: "Giant Poisonous Snake",
      index: "giant-poisonous-snake",
      armor_class: [
        {
          value: 14,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 3,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.25,
      constitution: 13,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 18,
    },
    {
      name: "Giant Scorpion",
      index: "giant-scorpion",
      armor_class: [
        {
          value: 15,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 3,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 3,
      constitution: 15,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 13,
    },
    {
      name: "Sea Hag",
      index: "sea-hag",
      armor_class: [
        {
          value: 14,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "chaotic evil",
      charisma: 13,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 2,
      constitution: 16,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 13,
    },
    {
      name: "Spider",
      index: "spider",
      armor_class: [
        {
          value: 12,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 2,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0,
      constitution: 8,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 14,
    },
    {
      name: "Giant Rat",
      index: "giant-rat",
      armor_class: [
        {
          value: 12,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 4,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.125,
      constitution: 11,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 15,
    },
    {
      name: "Giant Spider",
      index: "giant-spider",
      armor_class: [
        {
          value: 14,
          type: "natural",
        },
      ],
      desc:
        "To snare its prey, a giant spider spins elaborate webs or shoots sticky strands of webbing from its abdomen. Giant spiders are most commonly found underground, making their lairs on ceilings or in dark, web-filled crevices. Such lairs are often festooned with web cocoons holding past victims.",
      alignment: "unaligned",
      charisma: 4,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 1,
      constitution: 12,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 16,
    },
    {
      name: "Solar",
      index: "solar",
      armor_class: [
        {
          value: 21,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "lawful good",
      charisma: 30,
      condition_immunities: [
        {
          name: "Charmed",
          desc: [
            "- A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects.",
            "- The charmer has advantage on any ability check to interact socially with the creature.",
          ],
        },
        {
          name: "Exhaustion",
          desc: [
            "Some special abilities and environmental hazards, such as starvation and the long-term effects of freezing or scorching temperatures, can lead to a special condition called exhaustion. Exhaustion is measured in six levels. An effect can give a creature one or more levels of exhaustion, as specified in the effect's description.",
            "1 - Disadvantage on ability checks",
            "2 - Speed halved",
            "3 - Disadvantage on attack rolls and saving throws",
            "4 - Hit point maximum halved",
            "5 - Speed reduced to 0",
            "6 - Death",
            "If an already exhausted creature suffers another effect that causes exhaustion, its current level of exhaustion increases by the amount specified in the effect's description.",
            "A creature suffers the effect of its current level of exhaustion as well as all lower levels. For example, a creature suffering level 2 exhaustion has its speed halved and has disadvantage on ability checks.",
            "An effect that removes exhaustion reduces its level as specified in the effect's description, with all exhaustion effects ending if a creature's exhaustion level is reduced below 1.",
            "Finishing a long rest reduces a creature's exhaustion level by 1, provided that the creature has also ingested some food and drink.",
          ],
        },
        {
          name: "Frightened",
          desc: [
            "- A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.",
            "- The creature can't willingly move closer to the source of its fear.",
          ],
        },
        {
          name: "Poisoned",
          desc: [
            "- A poisoned creature has disadvantage on attack rolls and ability checks.",
          ],
        },
      ],
      proficiency_bonus: 7,
      challenge_rating: 21,
      constitution: 26,
      damage_immunities: ["necrotic", "poison"],
      damage_resistances: [
        "radiant",
        "bludgeoning, piercing, and slashing from nonmagical weapons",
      ],
      damage_vulnerabilities: [],
      dexterity: 22,
    },
    {
      name: "Stirge",
      index: "stirge",
      armor_class: [
        {
          value: 14,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 6,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 0.125,
      constitution: 11,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 16,
    },
    {
      name: "Giant Toad",
      index: "giant-toad",
      armor_class: [
        {
          value: 11,
          type: "dex",
        },
      ],
      desc: null,
      alignment: "unaligned",
      charisma: 3,
      condition_immunities: [],
      proficiency_bonus: 2,
      challenge_rating: 1,
      constitution: 13,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 13,
    },
    {
      name: "Gladiator",
      index: "gladiator",
      armor_class: [
        {
          value: 16,
          type: "armor",
        },
      ],
      desc:
        "Gladiators battle for the entertainment of raucous crowds. Some gladiators are brutal pit fighters who treat each match as a life-or-death struggle, while others are professional duelists who command huge fees but rarely fight to the death.",
      alignment: "any alignment",
      charisma: 15,
      condition_immunities: [],
      proficiency_bonus: 3,
      challenge_rating: 5,
      constitution: 16,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 15,
    },
    {
      name: "Stone Giant",
      index: "stone-giant",
      armor_class: [
        {
          value: 17,
          type: "natural",
        },
      ],
      desc: null,
      alignment: "neutral",
      charisma: 9,
      condition_immunities: [],
      proficiency_bonus: 3,
      challenge_rating: 7,
      constitution: 20,
      damage_immunities: [],
      damage_resistances: [],
      damage_vulnerabilities: [],
      dexterity: 15,
    },
  ];
}
